CREATE TABLE IF NOT EXISTS `ht_user` (
  `ht_user_id` varchar(30) DEFAULT NULL,
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `ht_number` smallint(5) UNSIGNED NOT NULL,
  `ht_user_ballov_p1` int(10) UNSIGNED DEFAULT NULL,
  `ht_user_maxballov_p1` int(10) UNSIGNED DEFAULT NULL,
  `q_nums_p1` smallint(5) UNSIGNED DEFAULT NULL,
  `q_num_now_p1` int(10) UNSIGNED DEFAULT NULL,
  `q_num_last_p1` int(10) UNSIGNED DEFAULT NULL,
  `ht_user_date_p1` date DEFAULT NULL,
  `ht_user_time_p1` time DEFAULT NULL,
  `ht_user_result1` mediumtext DEFAULT NULL,
  `ht_user_status_p1` varchar(20) DEFAULT NULL,
  `ht_user_ballov_p2` int(10) UNSIGNED DEFAULT NULL,
  `ht_user_maxballov_p2` int(10) UNSIGNED DEFAULT NULL,
  `ht_user_date_p2` date DEFAULT NULL,
  `ht_user_time_p2` time DEFAULT NULL,
  `q_nums_p2` smallint(5) UNSIGNED DEFAULT NULL,
  `q_num_now_p2` int(10) UNSIGNED DEFAULT NULL,
  `ht_user_result2` longtext DEFAULT NULL,
  `ht_user_status_p2` varchar(20) DEFAULT NULL,
  `ht_user_checker` bigint(20) UNSIGNED DEFAULT NULL,
  `ht_user_check_date` date DEFAULT NULL,
  `ht_user_tarif_num` int(11) DEFAULT NULL,
  `ht_user_apell_stud` mediumtext DEFAULT NULL,
  `ht_user_apell_teacher` mediumtext DEFAULT NULL,
  `timer_updated_at_p1` datetime(4) DEFAULT NULL,
  `timer_seconds_p1` double NOT NULL DEFAULT 0,
  `timer_updated_at_p2` datetime(4) DEFAULT NULL,
  `timer_seconds_p2` double NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`,`ht_number`) USING BTREE,
  KEY `ind_status_p1` (`ht_user_status_p1`),
  KEY `ind_status_p2` (`ht_user_status_p2`),
  KEY `ht_tar_num` (`ht_user_tarif_num`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `ht_user_p1` (
  `user_id` bigint(20) UNSIGNED NOT NULL,
  `ht_number` smallint(5) UNSIGNED NOT NULL,
  `q_number` tinyint(3) UNSIGNED NOT NULL,
  `dop` tinyint(1) NOT NULL DEFAULT 0,
  `q_id` smallint(5) UNSIGNED DEFAULT NULL,
  `q_type` tinyint(3) UNSIGNED DEFAULT NULL,
  `q_answer` varchar(50) DEFAULT NULL,
  `mix_rules` text DEFAULT NULL,
  `q_task_number` tinyint(3) UNSIGNED DEFAULT NULL,
  `real_ball` tinyint(3) UNSIGNED DEFAULT NULL,
  `user_answer` varchar(50) DEFAULT NULL,
  `user_ball` tinyint(3) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (`user_id`,`ht_number`,`q_number`,`dop`),
  KEY `ht_p1` (`user_id`,`ht_number`),
  KEY `ht_p1_q` (`user_id`,`ht_number`,`q_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `questions` (
  `q_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `q_type` int(10) UNSIGNED DEFAULT NULL,
  `q_question` mediumtext DEFAULT NULL,
  `q_answer` varchar(30) DEFAULT NULL,
  `q_description` mediumtext DEFAULT NULL,
  `q_task_number` int(10) UNSIGNED DEFAULT NULL,
  `q_chapter` varchar(50) DEFAULT NULL,
  `q_lesson_num` int(10) UNSIGNED DEFAULT NULL,
  `q_public` tinyint(1) DEFAULT NULL,
  `selfmade` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`q_id`),
  KEY `q_chapter_ind` (`q_chapter`),
  KEY `q_lesson_num_ind` (`q_lesson_num`),
  KEY `q_task_number_ind` (`q_task_number`),
  KEY `q_public_ind` (`q_public`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;